In [1]:
!pip install -q accelerate==0.21.0 peft==0.4.0 bitsandbytes==0.40.2 transformers==4.31.0 trl==0.4.7


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.2/244.2 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 kB 8.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.5/92.5 MB 15.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 76.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 kB 8.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 79.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 44.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 13.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 23.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 15.4 MB/s eta 0:00:00


In [2]:
import os
import torch
from datasets import load_dataset, Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    HfArgumentParser,
    TrainingArguments,
    pipeline,
    logging,
)
from peft import LoraConfig, PeftModel
from trl import SFTTrainer
import pandas as pd
import torch

In [3]:
from huggingface_hub import notebook_login
notebook_login()

In [4]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


### Data processing

In [8]:
train_data = pd.read_csv('/content/drive/MyDrive/224ndata/train_dataset.csv')
question = "Evaluate the completeness of the given story. Answer only with a proportion, in the form of a decimal. Do not include any other details. Story: "
dataset = Dataset.from_pandas(train_data)


def transform_story(example):
    story_text = example['story']
    error_position = example['chunk_prop']

    formatted_text = f'[INST] Evaluate the completeness of the given story. Answer only with a proportion, in the form of a decimal. Do not include any other details. Story: {story_text} [/INST] {error_position} '

    return {'text': formatted_text}

transformed_dataset = dataset.map(transform_story)
for i in range(5):
    print(transformed_dataset[i]['text'])

Map:   0%|          | 0/800 [00:00<?, ? examples/s]

[INST] Evaluate the completeness of the given story. Answer only with a proportion, in the form of a decimal. Do not include any other details. Story: It was a damp and dreary day in London when a telegram arrived at 221B Baker Street, summoning Sherlock Holmes and Dr. John Watson to a case that would test the limits of their deduction skills. The year was 1892, and the mystery surrounding the murder of Scott Eccles' host, Garcia, also known as the Tiger of San Pedro, was shrouded in darkness and intrigue.

With a sense of anticipation, Holmes and Watson made their way to the scene of the crime, a grand house in the outskirts of London where the gruesome murder had taken place. Miss Burnet, the governess of the household, met them with a look of fear and determination in her eyes. She revealed that she was part of a secret society seeking revenge on Garcia for his atrocities in San Pedro, a fact that sent shivers down the spines of both Holmes and Watson.

As they delved deeper into th

In [9]:

model_name = "meta-llama/Llama-2-7b-chat-hf"

### QLoRA parameters

# LoRA attention dimension
lora_r = 64

# Alpha parameter for LoRA scaling
lora_alpha = 16

# Dropout probability for LoRA layers
lora_dropout = 0.1

### bitsandbytes parameters

# Activate 4-bit precision base model loading
use_4bit = True

# Compute dtype for 4-bit base models
bnb_4bit_compute_dtype = "float16"

# Quantization type (fp4 or nf4)
bnb_4bit_quant_type = "nf4"

# Activate nested quantization for 4-bit base models (double quantization)
use_nested_quant = False

### TrainingArguments parameters

# Output directory where the model predictions and checkpoints will be stored
output_dir = "./results"

# Number of training epochs
num_train_epochs = 1

# Enable fp16/bf16 training (set bf16 to True with an A100)
fp16 = False
bf16 = False

# Batch size per GPU for training
per_device_train_batch_size = 4

# Batch size per GPU for evaluation
per_device_eval_batch_size = 4

# Number of update steps to accumulate the gradients for
gradient_accumulation_steps = 1

# Enable gradient checkpointing
gradient_checkpointing = True

# Maximum gradient normal (gradient clipping)
max_grad_norm = 0.3

# Initial learning rate (AdamW optimizer)
learning_rate = 2e-4

# Weight decay to apply to all layers except bias/LayerNorm weights
weight_decay = 0.001

# Optimizer to use
optim = "paged_adamw_32bit"

# Learning rate schedule
lr_scheduler_type = "cosine"

# Number of training steps (overrides num_train_epochs)
max_steps = -1

# Ratio of steps for a linear warmup (from 0 to learning rate)
warmup_ratio = 0.03

# Group sequences into batches with same length
# Saves memory and speeds up training considerably
group_by_length = True

# Save checkpoint every X updates steps
save_steps = 0

# Log every X updates steps
logging_steps = 25

### SFT parameters

# Maximum sequence length to use
max_seq_length = None

# Pack multiple short examples in the same input sequence to increase efficiency
packing = False

# Load the entire model on the GPU 0
device_map = {"": 0}

In [10]:
# Load tokenizer and model with QLoRA configuration
compute_dtype = getattr(torch, bnb_4bit_compute_dtype)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=use_4bit,
    bnb_4bit_quant_type=bnb_4bit_quant_type,
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=use_nested_quant,
)

# Check GPU compatibility with bfloat16
if compute_dtype == torch.float16 and use_4bit:
    major, _ = torch.cuda.get_device_capability()
    if major >= 8:
        print("=" * 80)
        print("Your GPU supports bfloat16: accelerate training with bf16=True")
        print("=" * 80)

# Load base model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map=device_map
)
model.config.use_cache = False
model.config.pretraining_tp = 1

# Load LLaMA tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right" # Fix weird overflow issue with fp16 training

# Load LoRA configuration
peft_config = LoraConfig(
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    r=lora_r,
    bias="none",
    task_type="CAUSAL_LM",
)

# Set training parameters
training_arguments = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=num_train_epochs,
    per_device_train_batch_size=per_device_train_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    optim=optim,
    save_steps=save_steps,
    logging_steps=logging_steps,
    learning_rate=learning_rate,
    weight_decay=weight_decay,
    fp16=fp16,
    bf16=bf16,
    max_grad_norm=max_grad_norm,
    max_steps=max_steps,
    warmup_ratio=warmup_ratio,
    group_by_length=group_by_length,
    lr_scheduler_type=lr_scheduler_type,
    report_to="tensorboard"
)

# Set supervised fine-tuning parameters
trainer = SFTTrainer(
    model=model,
    train_dataset=transformed_dataset,
    peft_config=peft_config,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    tokenizer=tokenizer,
    args=training_arguments,
    packing=packing,
)

# Train model
trainer.train()

# Save trained model
trainer.model.save_pretrained("Llama-2-7b-unresolved-error-finetuned")

model.eval()

config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.62k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/peft/utils/other.py:102: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py:159: UserWarning: You didn't pass a `max_seq_length` argument to the SFTTrainer, this will default to 1024
  warnings.warn(


Map:   0%|          | 0/800 [00:00<?, ? examples/s]

You're using a LlamaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 4096, padding_idx=0)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear4bit(
            in_features=4096, out_features=4096, bias=False
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.1, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=4096, out_features=64, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=64, out_features=4096, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
          )
          (k_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear4bit(
            in_features=4096, out_features=4096, bias=False
            (lora_dropout): ModuleDict(
              (default): 

In [11]:
test_df = pd.read_csv('/content/drive/MyDrive/224ndata/test_dataset.csv').reset_index(drop=True).dropna()
def remove_empty_lines(text):
  lines = text.split('\n')
  non_empty_lines = [line.strip() for line in lines if line.strip()]
  return '\n'.join(non_empty_lines)

# Apply the function to the text column
test_df['story'] = test_df['story'].apply(remove_empty_lines)
test_df['story_truncated'] = test_df['story_truncated'].apply(remove_empty_lines)

In [ ]:
import re
from tqdm import tqdm
y_true = []
y_pred = []
responses = []

for index, row in tqdm(test_df.iterrows(), total=test_df.shape[0]):
    story = row['story_truncated']
    proportion = row['chunk_prop']
    prompt = f"[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: {story} [/INST]"
    # Generate model output

    model_inputs = tokenizer(prompt, return_tensors="pt").to('cuda')
    output = model.generate(**model_inputs,  max_length=1024)
    print(output)
    response = tokenizer.decode(output[0], skip_special_tokens=True)

    print(response)
    responses.append(response)


    y_true.append(proportion)

  1%|          | 1/101 [00:31<52:01, 31.22s/it]

tensor([[    1,   518, 25580,  ..., 29946, 29955, 29900]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: In the secluded mountains behind Virginia, nestled in the mist-shrouded valleys where the trees whispered ancient secrets and the wind carried a haunting melody, there stood the stone house of Doomdorf. A man of dark repute, Doomdorf was known for his illicit liquor that held a devilish allure to those who dared to taste it. The locals whispered tales of his shady past and the chaos his hellish brew brought upon the community.
Uncle Abner, a wise and respected elder of the area, and Squire Randolph, a man of authority and influence, grew concerned about the impacts of Doomdorf's activities on the community. Together, they decided to confront the mysterious man and put an end to his nefarious deeds once and for all.
One fateful evening, they made their way to Do

  2%|▏         | 2/101 [01:35<1:23:47, 50.78s/it]

tensor([[    1,   518, 25580,  ..., 29955, 29941, 29953]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: Frances Wilton had been battling with her addiction to morphia for years, sinking deeper and deeper into its clutches until she reached her lowest point. Desperate to break free from the chains of her dependence, she sought out the help of Dr. Halifax, a renowned physician known for his unorthodox but effective methods of treating addiction.
Dr. Halifax took on Frances' case with determination and compassion, knowing the uphill battle she faced in overcoming her addiction. He devised a clever treatment plan that involved substituting morphia with strychnine, a potent tonic that mimicked some of the effects of the drug but without the addictive properties. [/INST] 0.47368421052631576 0.47368421052631576 0.47368421052631576 0.47368421052631576 0.47368421052631576

  3%|▎         | 3/101 [01:43<51:15, 31.39s/it]  

tensor([[    1,   518, 25580, 29962,  2661,  6490,   920,  4866,   278,  1494,
          5828,   338, 29892,   297,  4958,   310,  6492,  5849, 29889,   673,
           871,   408,   263, 18618, 29889,  1938,   451,  3160,   738,   916,
           270,  1187,  7497, 29889, 13740, 29901,   512,   278,  5192,   310,
          3681, 29892,   278,   451, 23308, 22161,  5835, 24021, 29892,  1085,
          7085, 29892,   322,   902, 20676,   715, 15048,  1009,  2446,  4337,
           297,   278,   528, 23626,   310,   278,   270,   292, 29891,  1090,
          2057,  9563,   449,  2998,   408,   376,  1576,  8168, 12652,  8481,
          1213,  2688,   750,   380, 18975,   263,  7618,  1455,  1842,   393,
          1033,  1735,   278,  3236,   310,  4955, 29892,   322,   278,   380,
          6926,   892,  1880,   408,   896,  7272,   287,   278, 18517,   310,
          1009,  1321,  7598, 29889,    13,  6816,   273,  8000, 29892,   278,
         27592,  6459,   573,  2998,   408, 21386,  

  4%|▍         | 4/101 [01:45<31:50, 19.70s/it]

tensor([[    1,   518, 25580, 29962,  2661,  6490,   920,  4866,   278,  1494,
          5828,   338, 29892,   297,  4958,   310,  6492,  5849, 29889,   673,
           871,   408,   263, 18618, 29889,  1938,   451,  3160,   738,   916,
           270,  1187,  7497, 29889, 13740, 29901,   450, 17724,  6575,  4320,
           263, 14294,   330,   677,  1549,   278, 19786, 29891,  5417,   310,
           278,  3300,  1233,  6729,  3946, 29915, 29879, 18296, 29892,  4486,
          9735,  1218,   278, 10329,   359,   393,   750,   604, 21245,   287,
          2629, 29889, 11386, 23166, 29892,   263,  4325, 26689,   363,   575,
           293, 17924,  2998,   363,   670, 15301,  3458,   322, 28430, 10977,
           363,  9493, 29892,  8389, 28655,   303,   278,   844,  8194, 29892,
           670,  3347,  3261,   798,   287,   297, 26702,   408,   540, 18994,
           287,   278,  9088,  1434,  1075, 29889,    13,   797,   697, 11155,
         29892,  6285, 29889,   341,  5059,   880, 2

  5%|▍         | 5/101 [02:19<39:28, 24.67s/it]

tensor([[    1,   518, 25580,  ..., 29955, 29947, 29906]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: In the quaint town of Willow Creek, Virginia, the first day of the circuit court brought together an unlikely trio of individuals who would soon find themselves embroiled in a captivating mystery. The pompous and well-dressed Reginald Blackwood, the rugged outdoorsman Jacob Hunter, and the tall, irascible old man Ezekiel Jenkins found themselves seated together in the courtroom, awaiting the proceedings of the day.
The case that captured their attention was the mysterious death of Duncan Moore, a well-respected elderly man in the community. His body had been discovered in the woods just outside of town, and rumors of foul play had been circulating amongst the townsfolk.
As the trial began, tensions ran high, and the three men found themselves drawn into the int

  6%|▌         | 6/101 [02:59<47:12, 29.81s/it]

tensor([[    1,   518, 25580,  ..., 29900, 29945, 29947]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: Prince Zaleski, a renowned investigator known for his sharp mind and keen intuition, was approached by a distressed nobleman seeking his help. The nobleman's family had been plagued by a series of tragic events – suicides and mysterious deaths that seemed inexplicable. Zaleski, intrigued by the challenge, agreed to take on the case.
As Zaleski delved into the investigation, he discovered a web of cryptic messages and symbols that seemed to connect the deaths to a secretive society. The symbols, etched in blood and hidden in the victims' rooms, pointed to a sinister organization with a dark agenda.
Determined to uncover the truth, Zaleski began decoding the messages and piecing together the clues. His investigations led him to a hidden chamber beneath the city, 

  7%|▋         | 7/101 [03:48<56:38, 36.15s/it]

tensor([[    1,   518, 25580,  ..., 29871, 29900, 29889]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: The fog hung low over the grounds of Abbey Grange, casting an eerie pall over the stately manor. Sherlock Holmes and Dr. John Watson hurried up the winding path, their footsteps echoing in the silence of the night. Inspector Stanley Hopkins had sent an urgent summons, and the duo wasted no time in responding.
As they entered the grand foyer, Lady Brackenstall awaited them, her eyes filled with a mixture of fear and desperation. She recounted the events of the previous evening in a trembling voice, describing how an intruder had broken into the house, murdered her husband, and fled into the darkness.
Holmes listened intently, his keen eyes taking in every detail of Lady Brackenstall's demeanor and surroundings. There was a tension in the air, a sense of unease t

  8%|▊         | 8/101 [04:44<1:05:48, 42.46s/it]

tensor([[    1,   518, 25580,  ...,   310, 22161,  6030]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: Captain Hank Barber stood on the dock, his eyes widening in shock as he watched a motor boat careen into Boston Harbour, crashing into the dock with a loud thud. Rushing over, he was met with a grisly sight - a dead man in a French naval uniform slumped over the wheel of the boat.
Detective Mallory and Dr. Clough were called to the scene, but the case proved to be a puzzling one. The dead man was identified as Langham Dudley, a wealthy ship owner with no known enemies or criminal ties. The cause of death was determined to be a Japanese poison, adding another layer of mystery to the already perplexing case.
In their frustration, Detective Mallory and Dr. Clough reached out to The Thinking Machine, a renowned scientist and problem-solver known for his brilliant d

  9%|▉         | 9/101 [05:16<1:00:01, 39.15s/it]

tensor([[    1,   518, 25580,  ..., 29945, 29955, 29900]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: It was a stormy night in the city, the rain pelting down relentlessly, creating a cacophony of sound that drowned out all other noise. Inside the Novella Beauty Parlor, the atmosphere was equally tumultuous. Miss Blanche Blaisdell, the renowned actress known for her beauty and talent, lay lifeless on the floor, her once vibrant eyes now dull and empty.
First Deputy O'Connor paced back and forth, his expression grim as he surveyed the scene. It was clear that this was no ordinary death. The circumstances surrounding Miss Blaisdell's demise were shrouded in mystery, and O'Connor knew that he needed the expertise of the brilliant scientist and investigator, Craig Kennedy, to unravel the truth.
Kennedy, however, was nowhere to be found. His laboratory was dark and 

 10%|▉         | 10/101 [06:06<1:04:34, 42.58s/it]

tensor([[    1,   518, 25580,  ..., 29896, 29962, 29871]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: The Rovigno country house had always been a place of elegance and tranquility, nestled in the rolling hills of the countryside. However, on the night of the fire, the peaceful atmosphere was shattered by flames that licked the sky and sent thick smoke billowing into the air. Kennedy and Jameson, two seasoned detectives known for their sharp wit and unyielding determination, arrived at the scene soon after the alarm was raised.
As they surveyed the charred remains of the once-grand estate, Kennedy's keen eyes caught sight of a peculiar device among the debris—an infernal machine, designed to cause destruction and chaos. Jameson, always the more cautious of the two, immediately sensed that this fire was no accident.
Their suspicions deepened when they learned tha

 11%|█         | 11/101 [07:03<1:10:20, 46.90s/it]

tensor([[    1,   518, 25580,  ...,   133,   141,   229]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: It was a foggy morning in London when Dr. Sterndale, a renowned African explorer, arrived at 221B Baker Street seeking the help of Sherlock Holmes. His rugged appearance and determined expression hinted at a troubled mind, and Holmes immediately sensed that this was no ordinary case.
As they sat in Holmes' study, Dr. Sterndale revealed the reason for his visit. He spoke of the Tregennis family, once a respected and happy household, now torn apart by a tragic event. Three siblings - Mortimer, George, and Brenda Tregennis - had been found in their sitting room in a state of madness, with Brenda dead from an apparent overdose of devil's-foot root, a rare and deadly poison found only in Africa.
Dr. Sterndale confessed to Holmes that he had been deeply in love with 

 12%|█▏        | 12/101 [07:44<1:07:04, 45.22s/it]

tensor([[    1,   518, 25580,  ..., 29953, 29953, 29953]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: The small mill-town of Oakridge was abuzz with whispers and speculation as news of Bradley Cushing's untimely death spread like wildfire. The young chemist had been found slumped over his laboratory bench, a look of terror frozen on his face. His colleagues were baffled, the town's residents were shocked, and the local authorities were at a loss for answers.
Enter Kennedy, a seasoned investigator known for his sharp wit and keen eye for detail. With a reputation for solving the most perplexing of cases, Kennedy was the town's last hope in unraveling the mystery surrounding Cushing's death. As he stepped into the laboratory where the young chemist had met his demise, Kennedy's mind raced with possibilities.
The laboratory was a scene of organized chaos, beakers 

 13%|█▎        | 13/101 [08:29<1:06:17, 45.20s/it]

tensor([[    1,   518, 25580,  ..., 29947, 29945, 29955]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: Miss Daphne Harding had always believed her family was ordinary in every way. They lived in a modest house on the outskirts of town, and their only notable possession was a beautiful antique bracelet that had been passed down through generations. Little did she know that this bracelet held the key to a hidden treasure that had been buried on the Harding estate for decades.
One stormy night, as the wind howled outside and rain lashed against the windows, Miss Harding was startled awake by the sound of breaking glass. Heart pounding, she crept downstairs to investigate, only to come face to face with a masked woman who demanded the treasured bracelet.
Terrified but determined, Miss Harding refused to hand over the heirloom. The masked woman's eyes glittered with 

 14%|█▍        | 14/101 [09:08<1:02:45, 43.28s/it]

tensor([[    1,   518, 25580,  ..., 29941, 29941, 29941]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: It was a brisk autumn day when J. Morgan Grayson, a prominent financier known for his astute business acumen, found himself facing a dilemma that threatened to unravel his entire empire. Sitting in his opulent office, with its mahogany desk and walls adorned with framed stock certificates, Grayson fumed as he recounted the recent string of financial losses that had plagued his firm.
Summoning all his resolve, Grayson picked up the telephone and dialed a number he had never thought he would need to call—the office of Professor Augustus S.F.X. Van Dusen, the enigmatic genius known far and wide as The Thinking Machine.
Within hours, the professor arrived at Grayson's office, his keen blue eyes taking in every detail with razor-sharp focus. Grayson wasted no time i

 15%|█▍        | 15/101 [09:53<1:02:44, 43.77s/it]

tensor([[    1,   518, 25580,  ..., 29871, 29896, 29871]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: The town of Brixton was known for its peaceful streets and close-knit community. However, all that changed when the news of Mrs. Vincent's murder spread like wildfire through the town. Pretty Mrs. Vincent, known for her kindness and elegance, had been found stabbed to the heart in her own home. The shock and horror that rippled through Brixton was palpable, and the townspeople were left reeling from the terrible crime that had shattered their sense of security.
The evidence found at the scene pointed towards a robbery gone wrong. Two hundred pounds were missing from the escritoire in Mrs. Vincent's study, leading the authorities to suspect that the motive behind the murder was greed. The prime suspect in the case was Julian Roy, a young man who had been seen sn

 16%|█▌        | 16/101 [10:29<58:38, 41.40s/it]  

tensor([[    1,   518, 25580,  ..., 22056,  4034,   297]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: Thorpe Hazell had always been fascinated by the intricate workings of mysteries, whether they be found in the pages of a book or unraveling in real life. As an amateur photographer with a keen eye for detail and a lover of rare books, Hazell often found himself drawn to unusual situations that required his unique skills of observation and deduction.
One crisp autumn morning, Hazell found himself in the quaint town of Leamington, camera slung over his shoulder and a new book tucked under his arm. Little did he know that this ordinary day would soon lead him into the heart of a daring railway mystery that would test his investigative prowess like never before.
It all began when Hazell overheard a conversation at the local railway station about a missing goods tru

 17%|█▋        | 17/101 [11:23<1:03:27, 45.33s/it]

tensor([[    1,   518, 25580,  ..., 29946, 29946, 29946]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: In the bustling streets of Brixton, a sense of unease lingered in the air following the shocking murder of Mrs. Vincent, the elegant wife of the affluent stockbroker, Paul Vincent. The news of the gruesome crime spread like wildfire, sending shockwaves through the tight-knit community. Detective X, known for his keen intellect and unwavering determination, was swiftly summoned to investigate the case that seemed to have no clear motive or suspect.
As Detective X delved into the intricate web of clues surrounding the murder, one name emerged as a potential suspect - Julian Roy, a close friend of Paul Vincent. Whispers in the neighborhood hinted at a strained relationship between Julian and Mrs. Vincent, leading many to speculate on his possible involvement in th

 18%|█▊        | 18/101 [12:07<1:02:03, 44.86s/it]

tensor([[    1,   518, 25580,  ..., 29947, 29945, 29955]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: Professor Kennedy sat at his desk, engrossed in a book on forensic psychology, when his assistant, Walter, brought in the day's mail. Among the usual assortment of letters and flyers, there was one that caught Kennedy's attention. It was a plea for help from a woman named Janet Cranston, who claimed to be held against her will in a private asylum called Belleclaire Sanatorium.
Kennedy's curiosity was piqued. He read the letter carefully, noting the desperation in the woman's words and the urgency of her situation. Without hesitation, he decided to take up the case and investigate the mysterious goings-on at Belleclaire Sanatorium.
Walter was skeptical at first, but he trusted Kennedy's instincts and agreed to assist him in the daring rescue mission. They made p

 19%|█▉        | 19/101 [12:54<1:02:09, 45.48s/it]

tensor([[    1,   518, 25580,  ..., 29906, 29941, 29947]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: The Hon. Staunton Toleron was a man of impeccable taste and connections, always one step ahead in the intricate dance of high society. So when he managed to secure a luxurious suite at the prestigious Hotel Cyril, it raised no eyebrows. His arrival was met with polite nods and deferential smiles, as befitting a man of his stature.
But as the sun dipped below the horizon and the city lights sparkled outside his window, the tranquility of the hotel was shattered by a frantic commotion. The famous actress Betty Barry, staying in the suite next to Toleron's, had discovered her precious jewels missing. Accusations flew, fingers pointed, and suspicion fell heavily on the Hon. Staunton Toleron.
Toleron's protests of innocence fell on deaf ears as the evidence seemed t

 20%|█▉        | 20/101 [13:42<1:02:35, 46.36s/it]

tensor([[    1,   518, 25580,  ..., 29871, 29900, 29889]], device='cuda:0')
[INST] Estimate how complete the following story is, in terms of plot development. Answer only as a proportion. Do not include any other detaisl. Story: Miss Brooke, a renowned detective with a sharp mind and a keen eye for detail, was enjoying a quiet afternoon at her cozy home when a knock on the door disrupted her peace. Inspector Clampe stood on her doorstep, his face a mix of urgency and intrigue.
"Miss Brooke, I need your assistance with a rather peculiar case that has come to our attention," Clampe explained, his voice tinged with anticipation.
Intrigued, Miss Brooke invited the inspector in and listened intently as he unraveled the details of the mystery. It all began with the theft of a valuable cheque from a local business owner. The unusual aspect of the case was a reported ghost sighting at the scene of the crime, adding a layer of intrigue to the already baffling situation.
As Miss Brooke delved de